### ISSUE TITLE
License

### ISSUE THREAD

**Issue by CesarERamosMedina** [Peter-Kocsis/IntrinsicImageDiffusion#1]
First of all, great results!
I assume that the license comes from the use of InteriorVerse on some parts of your research. I wonder if it would be possible to leave the code on an MIT License (as I believe it original was, from the git history), but leave the required-license-associated-parts under the required license?

**Comment by Peter-Kocsis** [comment]
Hi, thanks a lot! Unfortunately, we don't plan to change the license. It is not due to InteriorVerse, but because industrial funds were used during the project. In case of any questions, or specific requests, feel free to reach out.

**Comment by CesarERamosMedina** [comment]
Understood, and no worries. Great work! Thank you for your reply!
