### ISSUE TITLE
Error in the released checkpoint for material diffusion

### ISSUE THREAD

**Issue by HollyDQWang** [Peter-Kocsis/IntrinsicImageDiffusion#10]
Hi! Congrats on the great work and thanks for the code and model ckpt. When testing inference on material decomposition, I encountered the following issue:
`Error executing job with overrides: ['logger=console']
Traceback (most recent call last):
  File "/home/IntrinsicImageDiffusion/iid/material_diffusion/__main__.py", line 141, in main
    material_diffusion(cfg)
  File "/home/IntrinsicImageDiffusion/iid/material_diffusion/__main__.py", line 70, in material_diffusion
    model.load_state_dict(ckpt)
  File "/home/Documents/IntrinsicImageDiffusion/iid/material_diffusion/iid.py", line 315, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for IntrinsicImageDiffusion:
	Missing key(s) in state_dict: "diffusion_module.logvar". 
`

I thus wonder whether there's issue with the released model checkpoints?

**Comment by HollyDQWang** [comment]
I set strict=False to fix this error but still not sure why it happens in the first place.

**Comment by fantasy-byakuya** [comment]
I have same question

**Comment by Aureliano-qwer** [comment]
Me too. Is it solved now?

**Comment by ge79puv** [comment]
The same issue here, and I also set strict=False. However, the material estimation result is worse than that in their paper.

**Comment by lez-s** [comment]
comment out following code in file `IntrinsicImageDiffusion/iid/material_diffusion/ldm/ddpm.py` might help.
`self.logvar = nn.Parameter(self.logvar, requires_grad=False)`

**Comment by Peter-Kocsis** [comment]
Hi, thanks for pointing out this issue! I have checked the code and the solution of @lez-s should indeed solve it. I have updated the repo now and this issue should be gone.
