### ISSUE TITLE
Error in Stage 3 - Lighting Optimization

### ISSUE THREAD

**Issue by yejun688** [Peter-Kocsis/IntrinsicImageDiffusion#11]
Hi! Great work! When run
`python -m iid.lighting_optimization logger=console`

encounter show error
`  File "/data/IntrinsicImageDiffusion/iid/callbacks.py", line 110, in on_train_epoch_start
    self(datamodule=trainer.datamodule, trainer=trainer, logger=trainer.logger, pl_module=pl_module)
  File "/root/miniconda3/envs/iid/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
TypeError: __call__() got an unexpected keyword argument 'trainer`

all information as follow:
https://docs.google.com/document/d/1E4nNVz54EurCJGmerCX2e74Av6J3Uy3Mzi3jdQgMDCQ/edit?usp=sharing

**Comment by saberpoi** [comment]
same problem

**Comment by Peter-Kocsis** [comment]
Thanks a lot for reporting this issue. I will look into this in detail as soon as possible, but for now I have implemented a quick fix (commit a8a72b8aa21408f2f5f32d9b7c4e3c58431231af). If you have the opportunity, please let me know if it works.

**Comment by yejun688** [comment]
Peter. Thank you very much. it works.
