### ISSUE TITLE
Reproduce evaluation results

### ISSUE THREAD

**Issue by bobboli** [Peter-Kocsis/IntrinsicImageDiffusion#14]
Hi,

Does the repo contain scripts to reproduce the evaluation results in the paper (mainly table 1 and 2)? Based on the current repo, do I need to run the stage 2 for each image in the test set of InteriorVerse (which requires modifying material_diffusion.yaml for each input image) and get the metric statistics?

Thank you!

**Comment by Peter-Kocsis** [comment]
Hi, 
No, the repo does not contain the evaluation scripts. To get the metrics, you need to run it on the full test set (10 samples, averaging). 
If you have any questions, feel free to reach out!
