### ISSUE TITLE
Problems related to the codebase

### ISSUE THREAD

**Issue by snowflakewang** [Peter-Kocsis/IntrinsicImageDiffusion#3]
Hi, thank you for your brilliant work in indoor scene material estimation/generation!
I am interested in your codebase related to the diffusion model part. You use _**ldm**_ as the codebase to implement your model. If I want to add some self-defined modules to the standard diffusion model, does it mean that _**ldm**_ is more flexible to edit than _**diffusers**_?

Thanks a lot! :)

**Comment by Peter-Kocsis** [comment]
Hi, yes, that was my personal impression and that's the reason why I ussed ldm directly and not diffusers. Furthermore, I preferred using Pytorch Lightning, which is not clear how compatible is with diffusers.
