### ISSUE TITLE
How  to get render image

### ISSUE THREAD

**Issue by BlackJoke76** [Peter-Kocsis/IntrinsicImageDiffusion#4]
This is a wonderful work. Can you tell me how to get the pictures in stage3 lighting_optimization.

**Comment by Peter-Kocsis** [comment]
Hi, thanks! I just pushed a [script for rerendering](https://github.com/Peter-Kocsis/IntrinsicImageDiffusion?tab=readme-ov-file#rendering) using a fitted lighting checkpoint. If you have any other questions, feel free to reach out.
