### ISSUE TITLE
LatentFinetuneDiffusion

### ISSUE THREAD

**Issue by jiayuanlu** [Peter-Kocsis/IntrinsicImageDiffusion#7]
Hi! Thank you for your great work!
I am trying to run the inference of Material Diffusion stage, but there is no ldm folder. Is that from StableDiffusion?
Thanks!

**Comment by Peter-Kocsis** [comment]
Hi, yes, the ldm package is part of the stable-diffusion-sdkit:
```pip install stable-diffusion-sdkit==2.1.5 --no-deps```

**Comment by jiayuanlu** [comment]
Thanks! It works!
