### ISSUE TITLE
Model backbone release

### ISSUE THREAD

**Issue by Jialuo-Li** [Peter-Kocsis/IntrinsicImageDiffusion#9]
Hi! Great work! 
It seems that even the inference can't be done without releasing the model backbone. Do you plan to release the material diffusion model soon?

**Comment by Peter-Kocsis** [comment]
Hi! The model is already released, you can download it with the commands described here: https://github.com/Peter-Kocsis/IntrinsicImageDiffusion?tab=readme-ov-file#material-diffusion

**Comment by Jialuo-Li** [comment]
Ok I see. Thank you!
